[package]
name = "story"
version = "0.1.0"
authors = ["guidao"]

[dependencies]
reqwest = "*"
scraper = "*"
clap= "*"
url = "*"
lazy_static = "*"
rocket = "0.3.9"
rocket_codegen = "0.3.9"
rocket_contrib = "0.3.9"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
